# Generated by Django 4.2 on 2023-04-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='bitcoin',
            field=models.CharField(default='bc1qag2dva7c5wznevqlkt48pefs6dsjpg3gedurw3', max_length=120),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='ethereum',
            field=models.CharField(default='0xc2a71F379d43206Ca47b2d5668D40ffA241160DC', max_length=120),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='usdt_erc20',
            field=models.CharField(default='0xc2a71F379d43206Ca47b2d5668D40ffA241160DC', max_length=120),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='usdt_trc20',
            field=models.CharField(default='TCEjw4fDYdL2EfsQ5NhpuLxoJW9REkG8P8', max_length=120),
        ),
    ]
